# Generated by Django 5.2.6 on 2026-02-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoPasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, help_text='Deixe em branco se o animal ainda estiver neste pasto.', null=True, verbose_name='Data de Saída')),
                ('motivo', models.CharField(blank=True, help_text='Ex: Rodízio de Pastagem, Tratamento, Venda, etc.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Movimentação de Pasto',
                'verbose_name_plural': 'Movimentações de Pasto',
                'db_table': 'ControleRebanho_movimentacaopasto',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Pasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Pasto/Piquete')),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Área (Hectares)')),
                ('tipo_capim', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Capim')),
                ('data_ultimo_manejo', models.DateField(blank=True, null=True, verbose_name='Data Último Manejo (Corte/Adubação)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('capacidade_maxima_ua', models.IntegerField(blank=True, default=10, help_text='Unidade Animal que o pasto comporta.', null=True, verbose_name='Capacidade Máxima (UA)')),
            ],
            options={
                'verbose_name': 'Pasto/Piquete',
                'verbose_name_plural': 'Pastos/Piquetes',
                'db_table': 'ControleRebanho_pasto',
            },
        ),
    ]
