# Generated by Django 5.2.6 on 2026-02-12 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestrutura', '0001_initial'),
        ('rebanho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaopasto',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_pasto', to='rebanho.animal'),
        ),
        migrations.AddField(
            model_name='movimentacaopasto',
            name='pasto_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_pasto', to='infraestrutura.pasto', verbose_name='Pasto de Destino'),
        ),
        migrations.AddField(
            model_name='movimentacaopasto',
            name='pasto_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_pasto', to='infraestrutura.pasto', verbose_name='Pasto de Origem'),
        ),
    ]
