# Generated by Django 5.2.6 on 2025-10-26 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Lote')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Criação/Entrada no Pasto')),
                ('finalidade', models.CharField(choices=[('MATRIZES', 'Matrizes de Cria'), ('BEZERROS', 'Bezerros/Desmama'), ('RECRIA', 'Recria (Garrotes/Novilhas)'), ('TOUROS', 'Reprodutores'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Finalidade do Lote')),
            ],
            options={
                'verbose_name': 'Lote de Manejo',
                'verbose_name_plural': 'Lotes de Manejo',
            },
        ),
        migrations.CreateModel(
            name='Pasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Pasto/Piquete')),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Área (Hectares)')),
                ('tipo_capim', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Capim')),
                ('data_ultimo_manejo', models.DateField(blank=True, null=True, verbose_name='Data Último Manejo (Corte/Adubação)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('capacidade_maxima_ua', models.IntegerField(blank=True, default=10, help_text='Unidade Animal que o pasto comporta.', null=True, verbose_name='Capacidade Máxima (UA)')),
            ],
            options={
                'verbose_name': 'Pasto/Piquete',
                'verbose_name_plural': 'Pastos/Piquetes',
            },
        ),
        migrations.CreateModel(
            name='TipoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Custo',
                'verbose_name_plural': 'Categorias de Custos',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50, unique=True, verbose_name='Identificação')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Animal')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('situacao', models.CharField(choices=[('VIVO', 'Vivo'), ('VENDIDO', 'Vendido'), ('ABATIDO', 'Abatido'), ('MORTO', 'Morto (Baixa)'), ('SEMEM', 'Semem')], default='VIVO', max_length=10, verbose_name='Situação do Animal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='ControleRebanho.animal', verbose_name='Mãe')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='ControleRebanho.animal', verbose_name='Pai')),
                ('lote_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_no_lote', to='ControleRebanho.lote', verbose_name='Lote Atual')),
                ('pasto_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_atuais', to='ControleRebanho.pasto', verbose_name='Pasto Atual')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Abate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abate', models.DateField(verbose_name='Data do Abate')),
                ('peso_carcaca_quente', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso Carcaça Quente (Kg)')),
                ('rendimento_carcaca', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rendimento de Carcaça (%)')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Estimado da Carcaça (R$)')),
                ('destino_carcaca', models.CharField(max_length=255, verbose_name='Destino (Consumo Próprio, Açougue, etc.)')),
                ('animal', models.OneToOneField(limit_choices_to={'situacao': 'VIVO'}, on_delete=django.db.models.deletion.PROTECT, to='ControleRebanho.animal', verbose_name='Animal Abatido')),
            ],
            options={
                'verbose_name': 'Abate',
                'verbose_name_plural': 'Abates',
            },
        ),
        migrations.CreateModel(
            name='BaixaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_baixa', models.DateField(verbose_name='Data da Baixa (Morte)')),
                ('causa', models.CharField(choices=[('DOENCA', 'Doença'), ('ACIDENTE', 'Acidente'), ('VELHICE', 'Velhice'), ('PREDACAO', 'Predação'), ('OUTRO', 'Outro (Especificar nas Obs.)')], default='DOENCA', max_length=10, verbose_name='Causa da Morte')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Detalhes / Necrópsia')),
                ('animal', models.OneToOneField(limit_choices_to={'situacao': 'VIVO'}, on_delete=django.db.models.deletion.PROTECT, to='ControleRebanho.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Baixa de Animal',
                'verbose_name_plural': 'Baixas de Animais',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, help_text='Deixe em branco se o animal ainda estiver neste pasto.', null=True, verbose_name='Data de Saída')),
                ('motivo', models.CharField(blank=True, help_text='Ex: Rodízio de Pastagem, Tratamento, Venda, etc.', max_length=255, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_pasto', to='ControleRebanho.animal')),
                ('pasto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_pasto', to='ControleRebanho.pasto', verbose_name='Pasto de Destino')),
                ('pasto_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_pasto', to='ControleRebanho.pasto', verbose_name='Pasto de Origem')),
            ],
            options={
                'verbose_name': 'Movimentação de Pasto',
                'verbose_name_plural': 'Movimentações de Pasto',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='pasto_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_alocados', to='ControleRebanho.pasto', verbose_name='Pasto Atual'),
        ),
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pesagem', models.DateField(verbose_name='Data da Pesagem')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (Kg)')),
                ('evento', models.CharField(blank=True, max_length=50, verbose_name='Evento (Ex: Desmama, Anual)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pesagens', to='ControleRebanho.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Pesagem',
                'verbose_name_plural': 'Controle de Peso',
                'ordering': ['data_pesagem'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_custo', models.DateField(verbose_name='Data do Custo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantidade/Unidade')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_individuais', to='ControleRebanho.animal', verbose_name='Aplicado ao Animal')),
                ('pasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_manejo', to='ControleRebanho.pasto', verbose_name='Aplicado ao Pasto')),
                ('tipo_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_registrados', to='ControleRebanho.tipocusto', verbose_name='Categoria do Custo')),
            ],
            options={
                'verbose_name': 'Registro de Custo',
                'verbose_name_plural': 'Registros de Custos',
                'ordering': ['-data_custo'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('tipo', models.CharField(choices=[('FIXA', 'Fixa (Ex: Salário, Aluguel)'), ('VARIAVEL', 'Variável (Ex: Ração, Medicamentos, Reparos)')], default='VARIAVEL', max_length=10, verbose_name='Tipo de Despesa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ControleRebanho.categoriadespesa', verbose_name='Categoria')),
                ('registro_custo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ControleRebanho.registrodecusto', verbose_name='Registro de Custo Associado')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Reproducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cio', models.DateField(verbose_name='Data do Cio / Protocolo')),
                ('tipo', models.CharField(choices=[('IA', 'Inseminação Artificial (IA)'), ('IATF', 'Inseminação Artificial em Tempo Fixo (IATF)'), ('MONTA', 'Monta Natural')], default='IA', max_length=20, verbose_name='Tipo de Manejo')),
                ('codigo_semen', models.CharField(blank=True, max_length=50, verbose_name='Cód. Sêmen / Marca')),
                ('data_dg', models.DateField(blank=True, null=True, verbose_name='Data do DG')),
                ('resultado', models.CharField(choices=[('P', 'Prenhe'), ('V', 'Vazia'), ('N', 'Não Verificado')], default='N', max_length=10, verbose_name='Resultado DG')),
                ('data_parto_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista do Parto')),
                ('bezerro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_reproducao', to='ControleRebanho.animal', verbose_name='Bezerro Nascido')),
                ('matriz', models.ForeignKey(limit_choices_to={'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='reproducoes_matriz', to='ControleRebanho.animal', verbose_name='Matriz')),
                ('touro', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproducoes_touro', to='ControleRebanho.animal', verbose_name='Touro (se for monta)')),
            ],
            options={
                'verbose_name': 'Manejo Reprodutivo',
                'verbose_name_plural': 'Manejos Reprodutivos',
            },
        ),
        migrations.CreateModel(
            name='TarefaManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('data_prevista', models.DateField(verbose_name='Data Prevista')),
                ('tipo', models.CharField(choices=[('VA', 'Vacinação / Vermifugação'), ('RO', 'Rodízio de Pasto Sugerido'), ('GE', 'Geral / Outros')], default='GE', max_length=2, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ControleRebanho.animal', verbose_name='Animal (opcional)')),
                ('pasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ControleRebanho.pasto', verbose_name='Pasto (opcional)')),
            ],
            options={
                'verbose_name': 'Tarefa de Manejo',
                'verbose_name_plural': 'Tarefas de Manejo',
                'ordering': ['data_prevista', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='TratamentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tratamento', models.DateField(verbose_name='Data do Tratamento')),
                ('tipo_tratamento', models.CharField(choices=[('VAC', 'Vacina'), ('VERM', 'Vermifugação'), ('TRAT', 'Tratamento Específico')], default='VAC', max_length=4, verbose_name='Tipo de Tratamento')),
                ('produto', models.CharField(max_length=100, verbose_name='Produto/Medicamento')),
                ('dose', models.CharField(blank=True, max_length=50, verbose_name='Dose/Via')),
                ('descricao', models.TextField(blank=True, verbose_name='Observações')),
                ('data_proximo_tratamento', models.DateField(blank=True, null=True, verbose_name='Próxima Data Prevista')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='ControleRebanho.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Tratamento de Saúde',
                'verbose_name_plural': 'Tratamentos de Saúde',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('peso_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso de Venda (Kg)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total da Venda (R$)')),
                ('comprador', models.CharField(max_length=255, verbose_name='Comprador')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('animal', models.OneToOneField(limit_choices_to={'situacao': 'VIVO'}, on_delete=django.db.models.deletion.PROTECT, to='ControleRebanho.animal', verbose_name='Animal Vendido')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='CustoAnimalDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_alocado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Alocado (R$)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_alocados', to='ControleRebanho.animal', verbose_name='Animal Alocado')),
                ('registro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_alocacao', to='ControleRebanho.registrodecusto', verbose_name='Custo Fonte')),
            ],
            options={
                'verbose_name': 'Detalhe de Custo Alocado',
                'verbose_name_plural': 'Detalhes de Custos Alocados',
                'unique_together': {('registro_de_custo', 'animal')},
            },
        ),
    ]
