# Generated by Django 5.2.6 on 2026-02-12 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestrutura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50, unique=True, verbose_name='Identificação')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Animal')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('situacao', models.CharField(choices=[('VIVO', 'Vivo'), ('VENDIDO', 'Vendido'), ('MORTO', 'Morto (Baixa)'), ('SEMEM', 'Semem')], default='VIVO', max_length=10, verbose_name='Situação do Animal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='rebanho.animal', verbose_name='Mãe')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='rebanho.animal', verbose_name='Pai')),
                ('pasto_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_atuais', to='infraestrutura.pasto', verbose_name='Pasto Atual')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'db_table': 'ControleRebanho_animal',
            },
        ),
        migrations.CreateModel(
            name='BaixaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_baixa', models.DateField(verbose_name='Data da Baixa (Morte)')),
                ('causa', models.CharField(choices=[('DOENCA', 'Doença'), ('ACIDENTE', 'Acidente'), ('VELHICE', 'Velhice'), ('PREDACAO', 'Predação'), ('OUTRO', 'Outro (Especificar nas Obs.)')], default='DOENCA', max_length=10, verbose_name='Causa da Morte')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Detalhes / Necrópsia')),
                ('animal', models.OneToOneField(limit_choices_to={'situacao': 'VIVO'}, on_delete=django.db.models.deletion.PROTECT, to='rebanho.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Baixa de Animal',
                'verbose_name_plural': 'Baixas de Animais',
                'db_table': 'ControleRebanho_baixaanimal',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Lote')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Criação/Entrada no Pasto')),
                ('finalidade', models.CharField(choices=[('MATRIZES', 'Matrizes de Cria'), ('BEZERROS', 'Bezerros/Desmama'), ('RECRIA', 'Recria (Garrotes/Novilhas)'), ('TOUROS', 'Reprodutores'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Finalidade do Lote')),
                ('pasto_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_alocados', to='infraestrutura.pasto', verbose_name='Pasto Atual')),
            ],
            options={
                'verbose_name': 'Lote de Manejo',
                'verbose_name_plural': 'Lotes de Manejo',
                'db_table': 'ControleRebanho_lote',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='lote_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_no_lote', to='rebanho.lote', verbose_name='Lote Atual'),
        ),
    ]
