# Generated by Django 5.2.6 on 2026-06-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infraestrutura", "0002_initial"),
        ("rebanho", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={
                "ordering": ["identificacao"],
                "verbose_name": "Animal",
                "verbose_name_plural": "Animais",
            },
        ),
        migrations.AddField(
            model_name="animal",
            name="data_ultima_pesagem",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="peso_atual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Peso Atual (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="identificacao",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Identificação (Brinco)"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="lote_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animais",
                to="rebanho.lote",
                verbose_name="Lote Atual",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="nome",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("VIVO", "Vivo"),
                    ("VENDIDO", "Vendido"),
                    ("MORTO", "Morto (Baixa)"),
                    ("SEMEM", "Semem"),
                ],
                default="VIVO",
                max_length=10,
                verbose_name="Situação",
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["identificacao"], name="rebanho_ani_identif_dc5251_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["data_nascimento"], name="rebanho_ani_data_na_2d0e4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["situacao"], name="rebanho_ani_situaca_eb8776_idx"
            ),
        ),
    ]
