# Generated by Django 5.2.6 on 2026-02-12 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'db_table': 'ControleRebanho_categoriadespesa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CustoAnimalDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_alocado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Alocado (R$)')),
            ],
            options={
                'verbose_name': 'Detalhe de Custo Alocado',
                'verbose_name_plural': 'Detalhes de Custos Alocados',
                'db_table': 'ControleRebanho_custoanimaldetalhe',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('tipo', models.CharField(choices=[('FIXA', 'Fixa (Ex: Salário, Aluguel)'), ('VARIAVEL', 'Variável (Ex: Ração, Medicamentos, Reparos)')], default='VARIAVEL', max_length=10, verbose_name='Tipo de Despesa')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'db_table': 'ControleRebanho_despesa',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_custo', models.DateField(verbose_name='Data do Custo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantidade/Unidade')),
            ],
            options={
                'verbose_name': 'Registro de Custo',
                'verbose_name_plural': 'Registros de Custos',
                'db_table': 'ControleRebanho_registrodecusto',
                'ordering': ['-data_custo'],
            },
        ),
        migrations.CreateModel(
            name='TipoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Custo',
                'verbose_name_plural': 'Categorias de Custos',
                'db_table': 'ControleRebanho_tipocusto',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('peso_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso de Venda (Kg)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total da Venda (R$)')),
                ('comprador', models.CharField(max_length=255, verbose_name='Comprador')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'ControleRebanho_venda',
            },
        ),
    ]
