# Generated by Django 6.0.5 on 2026-05-23 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestrutura', '0002_initial'),
        ('rebanho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Receita',
                'verbose_name_plural': 'Categorias de Receitas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FluxoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento/Custo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Saída')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('tipo_saida', models.CharField(choices=[('DESPESA_GERAL', 'Despesa Geral (Administrativa/Operacional)'), ('REGISTRO_CUSTO', 'Custo Direto Produção (Alocado a Animal/Pasto)')], max_length=15, verbose_name='Origem do Fluxo de Saída')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
            ],
            options={
                'verbose_name': 'Fluxo de Saída',
                'verbose_name_plural': 'Fluxo de Saídas (Despesas)',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='FluxoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Entrada')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('origem_pagador', models.CharField(max_length=255, verbose_name='Comprador / Pagador')),
                ('tipo_entrada', models.CharField(choices=[('VENDA_ANIMAL', 'Venda de Animal'), ('RECEITA_GERAL', 'Receita Geral (Leite, Silagem, etc.)')], max_length=15, verbose_name='Origem do Fluxo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Fluxo de Entrada',
                'verbose_name_plural': 'Fluxo de Entradas (Receitas)',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='TipoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Custo',
                'verbose_name_plural': 'Categorias de Custos',
            },
        ),
        migrations.CreateModel(
            name='RegistroDeCusto',
            fields=[
                ('fluxosaida_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.fluxosaida')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantidade/Unidade')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_individuais', to='rebanho.animal', verbose_name='Aplicado ao Animal')),
                ('pasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_manejo', to='infraestrutura.pasto', verbose_name='Aplicado ao Pasto')),
                ('tipo_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_registrados', to='financeiro.tipocusto', verbose_name='Categoria do Custo')),
            ],
            options={
                'verbose_name': 'Registro de Custo',
                'verbose_name_plural': 'Registros de Custos',
            },
            bases=('financeiro.fluxosaida',),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('fluxosaida_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.fluxosaida')),
                ('tipo', models.CharField(choices=[('FIXA', 'Fixa (Ex: Salário, Aluguel)'), ('VARIAVEL', 'Variável (Ex: Ração, Medicamentos, Reparos)')], default='VARIAVEL', max_length=10, verbose_name='Tipo de Despesa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriadespesa', verbose_name='Categoria')),
                ('registro_de_custo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_associada', to='financeiro.registrodecusto', verbose_name='Registro de Custo Associado')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
            bases=('financeiro.fluxosaida',),
        ),
        migrations.CreateModel(
            name='ReceitaGeral',
            fields=[
                ('fluxoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.fluxoentrada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriareceita', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Receita Geral',
                'verbose_name_plural': 'Receitas Gerais',
            },
            bases=('financeiro.fluxoentrada',),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('fluxoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.fluxoentrada')),
                ('peso_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso de Venda (Kg)')),
                ('animal', models.OneToOneField(limit_choices_to={'situacao': 'VIVO'}, on_delete=django.db.models.deletion.PROTECT, to='rebanho.animal', verbose_name='Animal Vendido')),
            ],
            options={
                'verbose_name': 'Venda de Animal',
                'verbose_name_plural': 'Vendas de Animais',
            },
            bases=('financeiro.fluxoentrada',),
        ),
        migrations.CreateModel(
            name='CustoAnimalDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_alocado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Alocado (R$)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_alocados', to='rebanho.animal', verbose_name='Animal Alocado')),
                ('registro_de_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_alocacao', to='financeiro.registrodecusto', verbose_name='Custo Fonte')),
            ],
            options={
                'verbose_name': 'Detalhe de Custo Alocado',
                'verbose_name_plural': 'Detalhes de Custos Alocados',
                'unique_together': {('registro_de_custo', 'animal')},
            },
        ),
    ]
