# Generated by Django 6.0.5 on 2026-06-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocusto',
            options={'verbose_name': 'Tipo de Custo', 'verbose_name_plural': 'Tipos de Custos'},
        ),
    ]
