# Generated by Django 5.2.6 on 2026-02-12 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        ('infraestrutura', '0001_initial'),
        ('rebanho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoanimaldetalhe',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_alocados', to='rebanho.animal', verbose_name='Animal Alocado'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriadespesa', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='registrodecusto',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_individuais', to='rebanho.animal', verbose_name='Aplicado ao Animal'),
        ),
        migrations.AddField(
            model_name='registrodecusto',
            name='pasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_manejo', to='infraestrutura.pasto', verbose_name='Aplicado ao Pasto'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='registro_de_custo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.registrodecusto', verbose_name='Registro de Custo Associado'),
        ),
        migrations.AddField(
            model_name='custoanimaldetalhe',
            name='registro_de_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_alocacao', to='financeiro.registrodecusto', verbose_name='Custo Fonte'),
        ),
        migrations.AddField(
            model_name='registrodecusto',
            name='tipo_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_registrados', to='financeiro.tipocusto', verbose_name='Categoria do Custo'),
        ),
        migrations.AddField(
            model_name='venda',
            name='animal',
            field=models.OneToOneField(limit_choices_to={'situacao': 'VIVO'}, on_delete=django.db.models.deletion.PROTECT, to='rebanho.animal', verbose_name='Animal Vendido'),
        ),
        migrations.AlterUniqueTogether(
            name='custoanimaldetalhe',
            unique_together={('registro_de_custo', 'animal')},
        ),
    ]
