# Generated by Django 6.0.5 on 2026-05-23 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestrutura', '0002_initial'),
        ('rebanho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pesagem', models.DateField(verbose_name='Data da Pesagem')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (Kg)')),
                ('evento', models.CharField(blank=True, default='Cadastro de peso regular', max_length=50, verbose_name='Evento (Ex: Desmama, Anual, Repasse)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pesagens', to='rebanho.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Pesagem',
                'verbose_name_plural': 'Controle de Peso',
                'ordering': ['data_pesagem'],
            },
        ),
        migrations.CreateModel(
            name='Reproducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cio', models.DateField(verbose_name='Data do Cio / Protocolo')),
                ('escore', models.DecimalField(blank=True, decimal_places=1, help_text='Insira um valor entre 1 e 5', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Escore do Cio (1-5)')),
                ('tipo', models.CharField(choices=[('IA', 'Inseminação Artificial (IA)'), ('IATF', 'Inseminação Artificial em Tempo Fixo (IATF)'), ('MONTA', 'Monta Natural')], default='IATF', max_length=20, verbose_name='Tipo de Manejo')),
                ('codigo_semen', models.CharField(blank=True, max_length=50, verbose_name='Cód. Sêmen / Marca')),
                ('data_dg', models.DateField(blank=True, null=True, verbose_name='Data do DG')),
                ('resultado', models.CharField(choices=[('P', 'Prenha'), ('V', 'Vazia'), ('N', 'Não Verificado')], default='N', max_length=10, verbose_name='Resultado DG')),
                ('data_parto_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista do Parto')),
                ('bezerro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_reproducao', to='rebanho.animal', verbose_name='Bezerro Nascido')),
                ('matriz', models.ForeignKey(limit_choices_to={'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='reproducoes_matriz', to='rebanho.animal', verbose_name='Matriz')),
                ('touro', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproducoes_touro', to='rebanho.animal', verbose_name='Touro (se for monta)')),
            ],
            options={
                'verbose_name': 'Manejo Reprodutivo',
                'verbose_name_plural': 'Manejos Reprodutivos',
            },
        ),
        migrations.CreateModel(
            name='TarefaManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('data_prevista', models.DateField(verbose_name='Data Prevista')),
                ('tipo', models.CharField(choices=[('VA', 'Vacinação / Vermifugação'), ('RO', 'Rodízio de Pasto Sugerido'), ('GE', 'Geral / Outros')], default='GE', max_length=2, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rebanho.animal', verbose_name='Animal (opcional)')),
                ('pasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestrutura.pasto', verbose_name='Pasto (opcional)')),
            ],
            options={
                'verbose_name': 'Tarefa de Manejo',
                'verbose_name_plural': 'Tarefas de Manejo',
                'ordering': ['data_prevista', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='TratamentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tratamento', models.DateField(verbose_name='Data do Tratamento')),
                ('tipo_tratamento', models.CharField(choices=[('VAC', 'Vacina'), ('VERM', 'Vermifugação'), ('TRAT', 'Tratamento Específico')], default='VAC', max_length=4, verbose_name='Tipo de Tratamento')),
                ('produto', models.CharField(max_length=100, verbose_name='Produto/Medicamento')),
                ('dose', models.CharField(blank=True, max_length=50, verbose_name='Dose/Via')),
                ('descricao', models.TextField(blank=True, verbose_name='Observações')),
                ('data_proximo_tratamento', models.DateField(blank=True, null=True, verbose_name='Próxima Data Prevista')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='rebanho.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Tratamento de Saúde',
                'verbose_name_plural': 'Tratamentos de Saúde',
            },
        ),
    ]
