# Generated by Django 5.2.6 on 2026-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproducao',
            name='escore',
            field=models.IntegerField(blank=True, null=True, verbose_name='Escore do Cio (1-5)'),
        ),
    ]
