# Generated by Django 5.2.6 on 2026-02-17 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejo', '0002_reproducao_escore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproducao',
            name='escore',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Insira um valor entre 1 e 5', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Escore do Cio (1-5)'),
        ),
    ]
